appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: uhcXTpT+FrTopDCdT3X1Teuz7pnhF3fv4eJhQ+dJyeYf0x9x7h7piU3idbhEx/tdi9bA+6pNojMABFNwXOyfq7JqlKysa3ldN0ZAd0fvuxPDiN+p6i92a7ZTt7hVf4JHZicS9+EJdPvjlNUH3SvGEHyzRiGoMPgST9B9W5EP5qIUivUXTntN2PZi3l86V/VY0CRv3AbJkW9YncP11SRgj3XsdTWKcGllf1umggUfSqOamdYzeIejNZeN3NHCntzt+UYJg+vujylJUzd90gKX04udkfPK7aNc4oRJxmKskeLYwYxXummfAuWQmsjXdaSD3CKpIlNqJlJxk/o1nlEPAJQCxQNOivIaU2hmNHL5Hewq67seU/k0kyKSvRZM9kQoHHh1YU4pJxOpWuDdBkT2rsvAs2KEGZqVGcl3UEsx1F7j0TqkiPbuqzWr8Z9Ymr+07Byi7cp4T6GdwMg/wTyhmqZ+vzwGOEHOvr01a09GfBInRTaOURMtJH3dpwHxD3KuSpgrhphENx+p+Eg6K8uLdm457t2k4lhLQfsLYpyU6aCEmgvH6e5CoTj9PBQSFj1FikzntLHVGg6G/L92NGT+6y1yy8NMxZIBtlJgOpYRN4nD3rUoyQqWwKYphHB7NHNcr2tBDoTjfhWkBuSwNJupRzIw0/bMjulB8/CWXXxFHHI=}
conda_forge_output_validation: true
